### PR TITLE
DM-34685: Fixes for configs/dp02.yaml

### PR DESCRIPTION
**Pull request by fritzm**
- Update collection to 2.2i/runs/DP0.2
- Add lsst_vist, lsst_detector, lsst_tract, lsst_patch, lsst_band, and lsstd_filter
- Add "e-9" suffix to spectral range constants

### CODE REVIEW

**Comment by gpdf** [comment]
@fritzm Is there a reason this branch has not been merged?  I am pretty sure it reflects what was actually done for DP0.2.  @andy-slac reminded me of this today.

**Comment by timj** [comment]
The Jira ticket looks like it's awaiting review by @ctslater

**Comment by fritzm** [comment]
Yup.  Adding Colin at reviewer here also.

**Review by ctslater — APPROVED** [review]

**Comment by gpdf** [comment]
@fritzm Mergeable now?

**Comment by fritzm** [comment]
@gpdf it would seem so -- I will look after this today...

**Comment by timj** [comment]
I'm assuming I can in fact merge this?

**Comment by gpdf** [comment]
@timj On queue to answer before dinner

**Review by gpdf — APPROVED** [review]
My summary, to make sure that I understand:
* @fritzm  ran the real, production extraction of metadata for DP0.2 from this branch instead of from `main`.  So it's a _fait accompli_ and harmful (to people's understanding of what was done for DP0.2) that this was not merged.
* @timj just added parallel fixes to the units of the band ranges for the other two (defunct and unused) configs in the directory, on reasonable grounds of consistency.

I'm in favor of merging ASAP.

**Pull request merged**
